import { config } from '@letstri/oxlint-config/oxfmt'

export default config({
  // `plugins/index.json` is generated by `bun run plugins`, and the formatter
  // would rewrite it into a shape the generator does not produce — so every
  // regeneration would leave the tree dirty until someone ran `format` too.
  // The manifests beside it are hand-written and stay formatted.
  ignorePatterns: ['plugins/index.json'],
})
