import { createHash } from 'node:crypto'

/**
 * Writes the Homebrew formula for the current version to dist/release/druk.rb, with the
 * checksums of the archives `bun run release` produced. The release workflow runs this
 * between packaging and upload, so druk.rb ships as a release asset, and its `tap` job
 * commits that asset to letstri/homebrew-tap as Formula/druk.rb — when TAP_TOKEN is set,
 * which is the only thing that step needs and the only credential the release stores.
 * Without the secret the formula is still on the release, to be copied over by hand.
 *
 * The formula installs the prebuilt binary; brew never compiles druk, so a machine that
 * installs it this way needs neither Bun nor Node.
 */
const RELEASE_DIR = './dist/release'

const { version, description, homepage, license } = await Bun.file('./package.json').json()

const ARCHIVES = {
  'darwin-arm64': 'druk-darwin-arm64.zip',
  'darwin-x64': 'druk-darwin-x64.zip',
  'linux-arm64': 'druk-linux-arm64.tar.gz',
  'linux-x64': 'druk-linux-x64.tar.gz',
} as const

async function sha256(path: string): Promise<string> {
  const file = Bun.file(path)
  if (!(await file.exists())) {
    process.stderr.write(`missing archive: ${path} — run \`bun run release\` first\n`)
    process.exit(1)
  }
  return createHash('sha256')
    .update(new Uint8Array(await file.arrayBuffer()))
    .digest('hex')
}

const sums = Object.fromEntries(
  await Promise.all(
    Object.entries(ARCHIVES).map(async ([target, name]) => [
      target,
      await sha256(`${RELEASE_DIR}/${name}`),
    ]),
  ),
) as Record<keyof typeof ARCHIVES, string>

const base = `${homepage}/releases/download/v${version}`

// `brew audit --strict` fails a desc that opens with an article, and package.json's
// opens with "A". Trimming it here keeps one description in package.json rather than a
// second one spelled out for Homebrew, which would drift.
const desc = description
  .replace(/"/g, "'")
  .split('—')[0]!
  .trim()
  .replace(/^(a|an|the) /i, '')
  .replace(/^./, (c: string) => c.toUpperCase())

// No `version` stanza: brew reads the version out of the URLs, and audit calls one
// given here redundant. `version` is still what the test block asserts on — it is
// inferred, not absent.
const formula = `# Generated by scripts/formula.ts — do not edit by hand.
class Druk < Formula
  desc "${desc}"
  homepage "${homepage}"
  license "${license}"

  on_macos do
    on_arm do
      url "${base}/${ARCHIVES['darwin-arm64']}"
      sha256 "${sums['darwin-arm64']}"
    end
    on_intel do
      url "${base}/${ARCHIVES['darwin-x64']}"
      sha256 "${sums['darwin-x64']}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/${ARCHIVES['linux-arm64']}"
      sha256 "${sums['linux-arm64']}"
    end
    on_intel do
      url "${base}/${ARCHIVES['linux-x64']}"
      sha256 "${sums['linux-x64']}"
    end
  end

  def install
    bin.install "druk"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/druk --version")
  end
end
`

await Bun.write(`${RELEASE_DIR}/druk.rb`, formula)
process.stdout.write(`wrote ${RELEASE_DIR}/druk.rb\n`)
